apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: cicd-integration
spec:
  selector:
    matchLabels:
      app: cicd-integration-k8s
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: cicd-integration-k8s
    spec:
      containers:
        - name: cicd-integration-k8s
          image: mahaveerkolekar8/cicd-integration # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080 # The port that the container is running on in the cluster


---

apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: cicd-integration-k8ssvc
spec:
  selector:
    app: cicd-integration-k8s
  ports:
    - protocol: "TCP"
      port: 8080 # The port that the service is running on in the cluster
      targetPort: 8080 # The port exposed by the service
  type: NodePort # type of the service.